# Generated by Django 3.2.4 on 2021-06-27 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.TextField(blank=True, max_length=600, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_step', to='ecm.step')),
            ],
        ),
        migrations.RemoveField(
            model_name='visa',
            name='candidate',
        ),
        migrations.AddField(
            model_name='candidate',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='can_stream', to='ecm.stream'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='note',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.DeleteModel(
            name='Ielts',
        ),
        migrations.DeleteModel(
            name='Visa',
        ),
        migrations.AddField(
            model_name='activity',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_can', to='ecm.candidate'),
        ),
        migrations.AddField(
            model_name='activity',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_stage', to='ecm.step'),
        ),
    ]
