# Generated by Django 3.2.4 on 2021-07-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc_type',
            new_name='document_type',
        ),
    ]
