# Generated by Django 3.2.4 on 2021-06-28 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0002_auto_20210627_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='act_stream', to='ecm.stream'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='act_stage', to='ecm.stage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_step', to='ecm.step'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
