# Generated by Django 3.2.4 on 2021-07-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0004_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='visibility',
            field=models.ManyToManyField(blank=True, to='ecm.UserGroup'),
        ),
    ]
