# Generated by Django 3.2.4 on 2021-07-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0005_alter_comment_comment_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='stage',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='stage',
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='act_status', to='ecm.stage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_step', to='ecm.step'),
        ),
    ]
