# Generated by Django 3.2.4 on 2021-07-04 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ecm', '0006_auto_20210703_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=70, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=290, null=True)),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='can_stream', to='ecm.stream')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(max_length=600, null=True)),
                ('comment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_comment', to='accounts.admin')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_can', to='ecm.item')),
            ],
        ),
        migrations.RenameModel(
            old_name='Stage',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_by',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='candidate',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='activity',
            name='item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='activity_can', to='ecm.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='doc_can', to='ecm.item'),
            preserve_default=False,
        ),
    ]
