# Generated by Django 3.2.4 on 2021-08-31 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ecm', '0006_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='act_added', to='accounts.admin'),
        ),
    ]
